### ISSUE TITLE
Team with the point is punished for triggering combat after revival

### ISSUE THREAD

**Issue by mlms13** [fponticelli/combattabletennis#2]
Scenario:
1. Team A serves, Team B fails to return: Team A is +1
2. The ball hits the ground: Team A is still +1 (0 points scored during combat)
3. Team B revives on the first bounce: Team A is still +1 (0 points scored during revival)
4. A normal phase begins
5. Team A hits the ball directly at a member of Team B and makes contact

With the phases and scoring that I've described in the rules so far, technically Team B wins the normal phase that began in step 4 because Team A doesn't make contact with the table when they begin the combat phase in step 5.

If they had continued the normal phase, they would have had a chance to accumulate more points. By ending (losing, by our current definition) the normal phase and beginning a (winning) combat phase, they forfeit their chance to accumulate points. This punishment seems unnecessary.

**Comment by mlms13** [comment]
Possible solution: "normal" and "combat" aren't separate phases with (potentially) separate winners. In this scenario, how does the point resolve if Team A serves the ball directly into the ground and it bounces twice?  We all agree that the point has ended then, but why (in rules) does Team B win the point?

**Comment by fponticelli** [comment]
Is this now to be closed?

**Comment by mlms13** [comment]
Ah yes, I think so. The revision where counters are never reset to 0 should take care of this.
